# Generated by Django 3.2.13 on 2022-08-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0018_dashboard_reference_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='reference_layer_identifier',
        ),
    ]
