# Generated by Django 3.2.13 on 2022-08-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0021_indicator_value_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='aggregation_behaviour',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='dashboard_link',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='reporting_level',
        ),
        migrations.RemoveField(
            model_name='indicatorgroup',
            name='dashboard_link',
        ),
        migrations.DeleteModel(
            name='IndicatorFrequency',
        ),
    ]
