# Generated by Django 3.2.13 on 2022-08-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0022_auto_20220803_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardindicatorrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicatorrule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
