# Generated by Django 3.2.13 on 2022-08-15 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0025_dashboardbookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardbookmark',
            options={'ordering': ('name',)},
        ),
    ]
