# Generated by Django 3.2.13 on 2022-08-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0027_auto_20220817_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlayerfield',
            name='type',
            field=models.CharField(default='string', max_length=512),
        ),
        migrations.AddField(
            model_name='dashboardcontextlayerfield',
            name='type',
            field=models.CharField(default='string', max_length=512),
        ),
    ]
