# Generated by Django 3.2.13 on 2022-08-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0028_auto_20220817_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlayer',
            name='label_styles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contextlayerfield',
            name='as_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardcontextlayer',
            name='label_styles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardcontextlayerfield',
            name='as_label',
            field=models.BooleanField(default=False),
        ),
    ]
