# Generated by Django 3.2.13 on 2022-08-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0029_auto_20220819_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlayer',
            name='url',
            field=models.CharField(help_text="Can put full url with parameters and system will use that. Or system will use 'CONTEXT LAYER PARAMETERS' if there is no parameters on the url.", max_length=10240),
        ),
    ]
