# Generated by Django 3.2.13 on 2022-08-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0030_alter_contextlayer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardIndicatorLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('visible_by_default', models.BooleanField(default=False)),
                ('group', models.CharField(blank=True, max_length=512, null=True)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('style', models.TextField(blank=True, help_text='This is specifically used for multi indicators layer.For single layer, it will use rule of indicator', null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_data.dashboard')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='dashboardindicator',
            options={'ordering': ('object__name',)},
        ),
        migrations.CreateModel(
            name='DashboardIndicatorLayerIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('color', models.CharField(blank=True, default='#000000', max_length=16, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_data.indicator')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_data.dashboardindicatorlayer')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
