# Generated by Django 3.2.13 on 2022-08-24 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0032_dashboard_layer_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardbookmark',
            name='selected_indicator_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geosight_data.dashboardindicatorlayer'),
        ),
    ]
