# Generated by Django 3.2.13 on 2022-08-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0034_dashboard_bookmark_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardbookmark',
            name='selected_indicators',
        ),
    ]
