# Generated by Django 3.2.13 on 2022-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0037_auto_20220907_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='date_filter_type',
            field=models.CharField(choices=[('No filter', 'No filter (global latest values will be used)'), ('Global datetime filter', 'Use datetime filter from Dashboard level.'), ('Custom filter', 'Use custom datetime filter.')], default='No filter', max_length=256),
        ),
        migrations.AddField(
            model_name='widget',
            name='date_filter_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
