# Generated by Django 3.2.13 on 2022-11-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0040_auto_20221121_0339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codelist',
            options={'verbose_name': 'Codelist', 'verbose_name_plural': 'Codelists'},
        ),
    ]
