# Generated by Django 3.2.13 on 2022-09-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_permission', '0002_permission_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencelayerindicatorpermission',
            name='organization_permission',
            field=models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Write', 'Write')], default='Read', max_length=16),
        ),
        migrations.AlterField(
            model_name='referencelayerindicatorpermission',
            name='public_permission',
            field=models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Write', 'Write')], default='Read', max_length=16),
        ),
    ]
