# Generated by Django 3.2.13 on 2022-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_permission', '0003_auto_20220916_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencelayerindicatorpermission',
            name='organization_permission',
            field=models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Write', 'Write')], default='None', max_length=16),
        ),
        migrations.AlterField(
            model_name='referencelayerindicatorpermission',
            name='public_permission',
            field=models.CharField(choices=[('None', 'None'), ('Read', 'Read'), ('Write', 'Write')], default='None', max_length=16),
        ),
    ]
