# Generated by Django 3.2.13 on 2022-09-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_data', '0037_auto_20220907_0325'),
        ('geosight_georepo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLayerIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_data.indicator')),
                ('reference_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayer')),
            ],
            options={
                'unique_together': {('reference_layer', 'indicator')},
            },
        ),
    ]
