# Generated by Django 3.2.13 on 2022-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_georepo', '0002_referencelayerindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencelayer',
            name='name',
            field=models.CharField(blank=True, help_text='Reference layer name.', max_length=256, null=True),
        ),
    ]
