# Generated by Django 3.2.13 on 2022-09-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_user_role_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeosightGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
        ),
    ]
