# Generated by Django 3.2.13 on 2022-11-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_geosightgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='indicator_no_data_fill_color',
            field=models.CharField(default='#D8D8D8', help_text='Fill color for indicator no data.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='indicator_no_data_outline_color',
            field=models.CharField(default='#000000', help_text='Outline color for indicator no data.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='indicator_other_data_fill_color',
            field=models.CharField(default='#A6A6A6', help_text='Fill color for indicator other data.', max_length=16),
        ),
        migrations.AddField(
            model_name='sitepreferences',
            name='indicator_other_data_outline_color',
            field=models.CharField(default='#000000', help_text='Outline color for indicator other data.', max_length=16),
        ),
    ]
