# Generated by Django 3.2.13 on 2022-11-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221103_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='disclaimer',
            field=models.TextField(default='The boundaries and names shown and the designations used on this map do not imply official endorsement or acceptance by the United Nations.'),
        ),
    ]
