# Generated by Django 3.2.13 on 2022-08-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_harvester', '0002_alter_harvester_harvester_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harvesterattribute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='harvesterattribute',
            name='harvester',
        ),
        migrations.RemoveField(
            model_name='harvesterlog',
            name='harvester',
        ),
        migrations.AlterUniqueTogether(
            name='harvestermappingvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='harvestermappingvalue',
            name='harvester',
        ),
        migrations.DeleteModel(
            name='Harvester',
        ),
        migrations.DeleteModel(
            name='HarvesterAttribute',
        ),
        migrations.DeleteModel(
            name='HarvesterLog',
        ),
        migrations.DeleteModel(
            name='HarvesterMappingValue',
        ),
    ]
