# Generated by Django 3.2.13 on 2022-08-05 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geosight_georepo', '0001_initial'),
        ('geosight_data', '0022_auto_20220803_0859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geosight_harvester', '0003_auto_20220803_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('harvester_class', models.CharField(choices=[('geosight.harvester.harveters.api_with_geography_and_today_date.APIWithGeographyAndTodayDate', 'API With Geography Using Today Date'), ('geosight.harvester.harveters.api_with_geography_and_date.APIWithGeographyAndDate', 'API With Geography And Date'), ('geosight.harvester.harveters.sharepoint_harvester.SharepointHarvester', 'Sharepoint File'), ('geosight.harvester.harveters.using_exposed_api.UsingExposedAPI', 'Harvested using exposed API by external client'), ('geosight.harvester.harveters.excel_harvester.ExcelHarvester', 'Excel Harvesters')], help_text='The type of harvester that will be used.Use class with full package.', max_length=256)),
                ('active', models.BooleanField(default=True, help_text='Make this harvester ready to be harvested.')),
                ('admin_level', models.IntegerField(default=0)),
                ('frequency', models.IntegerField(blank=True, help_text='The frequency in days that the harvester will run.', null=True)),
                ('creator', models.ForeignKey(blank=True, help_text='User who run the harvester.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geosight_data.indicator')),
                ('reference_layer', models.ForeignKey(help_text='Reference layer.', on_delete=django.db.models.deletion.CASCADE, to='geosight_georepo.referencelayer')),
            ],
        ),
        migrations.CreateModel(
            name='HarvesterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='This is when the harvester is started.')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Error', 'Error'), ('Done', 'Done')], default='Running', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, help_text='The detail of the harvesters. Should be filled with array so can construct the data in array.', null=True)),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_harvester.harvester')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.CreateModel(
            name='HarvesterMappingValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_value', models.CharField(help_text='The original value from remote', max_length=512)),
                ('platform_value', models.CharField(help_text='The platform value', max_length=512)),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_harvester.harvester')),
            ],
            options={
                'unique_together': {('harvester', 'remote_value')},
            },
        ),
        migrations.CreateModel(
            name='HarvesterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of attribute', max_length=256)),
                ('value', models.CharField(blank=True, help_text='The value of attribute', max_length=512, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='harvester/attributes')),
                ('harvester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geosight_harvester.harvester')),
            ],
            options={
                'unique_together': {('harvester', 'name')},
            },
        ),
    ]
