# Generated by Django 3.2.13 on 2022-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_harvester', '0006_auto_20220907_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='harvester_class',
            field=models.CharField(choices=[('geosight.harvester.harveters.api_with_geography_and_today_date.APIWithGeographyAndTodayDate', 'API With Geography Using Today Date'), ('geosight.harvester.harveters.api_with_geography_and_date.APIWithGeographyAndDate', 'API With Geography And Date'), ('geosight.harvester.harveters.sharepoint_harvester.SharepointHarvester', 'Sharepoint File'), ('geosight.harvester.harveters.using_exposed_api.UsingExposedAPI', 'Harvested using exposed API by external client'), ('geosight.harvester.harveters.excel_harvester.ExcelHarvester', 'Excel Harvesters')], help_text='The type of harvester that will be used.Use class with full package.', max_length=256),
        ),
        migrations.AlterField(
            model_name='harvesterlog',
            name='status',
            field=models.CharField(choices=[('Start', 'Start'), ('Running', 'Running'), ('Error', 'Error'), ('Done', 'Done')], default='Start', max_length=100),
        ),
    ]
