# Generated by Django 2.2.12 on 2020-07-03 09:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('geosight_harvester', '0008_alter_harvester_harvester_class'),
    ]

    # TODO:
    #  Always change gwmlw/models/views/well/Well.py when this has changed

    sql = """
            UPDATE geosight_harvester_harvester 
            SET harvester_class='geosight.harvester.harveters.excel_harvester_wide_format.ExcelHarvesterWideFormat' 
            WHERE harvester_class='geosight.harvester.harveters.excel_harvester.ExcelHarvester'
        """

    operations = [
        migrations.RunSQL(sql)
    ]
