# Generated by Django 3.2.13 on 2022-10-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geosight_harvester', '0009_migrate_excel_harvester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='harvester_class',
            field=models.CharField(choices=[('geosight.harvester.harveters.api_with_geography_and_today_date.APIWithGeographyAndTodayDate', 'API With Geography Using Today Date'), ('geosight.harvester.harveters.api_with_geography_and_date.APIWithGeographyAndDate', 'API With Geography And Date'), ('geosight.harvester.harveters.sharepoint_harvester.SharepointHarvester', 'Sharepoint File'), ('geosight.harvester.harveters.using_exposed_api.UsingExposedAPI', 'Harvested using exposed API by external client'), ('geosight.harvester.harveters.vector_context_layer_harvester.VectorContextLayerHarvester', 'Vector Context Layer Harvester'), ('geosight.harvester.harveters.excel_harvester_wide_format.ExcelHarvesterWideFormat', 'Import data from Excel (WIDE format)'), ('geosight.harvester.harveters.excel_harvester_long_format.ExcelHarvesterLongFormat', 'Import data from Excel (LONG format)')], help_text='The type of harvester that will be used.Use class with full package.', max_length=256),
        ),
    ]
